networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s

  connect:
    image: confluentinc/cp-kafka-connect:latest
    volumes:
      - ./schemas:/data/schemas
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    networks:
      - kafka-net
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:9092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
    command:
      - bash
      - -c
      - |
        echo "Waiting for Kafka to be ready..."
        sleep 40
        # Install the Datagen connector
        confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:latest
        # Start Kafka Connect service
        /etc/confluent/docker/run
    healthcheck:
      test: ["CMD", "curl", "-f", "http://connect:8083"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
    networks:
      - kafka-net
    ports:
    - "9005:9005"
    - "8081:8081"

  init-connectors:
    image: confluentinc/cp-kafka-connect:latest
    depends_on:
      kafka:
        condition: service_healthy
      connect:
        condition: service_healthy
    volumes:
      - ./backend/scripts/register-connectors.sh:/scripts/register-connectors.sh
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        echo "Waiting for Kafka Connect to be ready..."
        sleep 20
        chmod +x /scripts/register-connectors.sh
        /scripts/register-connectors.sh
    networks:
      - kafka-net
